language: node_js
node_js:
- 7.2.0
deploy:
  provider: heroku
  api_key:
    secure: P7M//zTSOsiBhERmXRGEX3hpvBPgKCoWUJyEowfNAny+RwmrugHyMYLtHgbW0nMiU7z97XyGfXp2TJyQ3VNmwx2fBCslj2OMQLWaN4KOjmgUS3i17m/QFl8H1DB1AqMl8dC1iUTxJi/JqZcU3yphqVrzXL25vUq9FPGlA0N4OKd6YhO6n9FBHqq+WC/V2870MFmBr8PjVacbWO23YlBT8HYIScePpaxU9esXRw/darpw4TIkNYZMnnxftnkp2klBylOXmrxDNbKT0ctf2UXeUJ2WNoCOWblEgicoMozPOebdCWiMsO9UXrnPA4jH2itOlqUj13nz7Vy+CduvMDS9M4aby8M2SSfnqS2Qkf+ihOpllUjG0WDg1Cn0dI7iAFsmIfK22lrfNvsFicqpsfpWKSavR69Z/u2LAjhsIwYhRgP4vBAKFXHspIjek7bmG0vzsmRgod5zvKJn7Ky8/hNWhvmCXRfkzMagpPd5cEyxbFXGhEpguhuGOyXOPf/2dS2xbr5gIgMTeNiXB56NeorqdGWT0e0UhTVZ+YwMTeGTGF9rmapa2Vs2rBwihMq3LWUVsPTt2PYVwXLk9kTovaPrPzhWL/7z7yLHEOziYdjfs9/yPWM9NWCLW74Yrn4yrEBC5pZClQWiQmJTqtXYcZq2EOzJqDecylGVMnNWpp8AcQ8=
  app: treasure-hunt-pns
